export const STORAGE_KEYS = {
  CODE_FRAMEWORK_KEY: 'CODE_FRAMEWORK_KEY',
  CSS_STYLE_KEY: 'CSS_STYLE_KEY',
  UNIT_TYPE_KEY: 'UNIT_TYPE_KEY',
  USER_COMPONENT_SETTINGS_KEY: 'USER_COMPONENT_SETTINGS_KEY'
} as const
